name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      working-directory: ${{ github.workspace }}
      run: |
        pip install -r $GITHUB_WORKSPACE/app/requirements.txt -t package
        cp $GITHUB_WORKSPACE/app/lambda_function.py package/
        cd package && zip -r ../lambda.zip .

    - name: Set up dependencies for AWS CLI
      run: |
        pip install --upgrade pip
        pip install awscli boto3

    - name: Fazer deploy na Lambda
      run: |
        aws lambda update-function-code \
          --function-name calculadora_teste_sintetico \
          --zip-file fileb://lambda.zip
